swagger: "2.0"
info:
  description: "API services that deliver a list of pharmacies by commune"
  version: "1.0.0"
  title: "[Pharmacies on duty] - API for availability pharmacies on duty by commune"

basePath: "/information"
tags:
- name: "Availability"
  description: "Shift pharmacies by commune"
schemes:
- "https"
paths:
  "/pharmaciesInShift":
     post:
      tags:
        - "Availability"
      summary: "Availability"
      description: ""
      operationId: "/pharmaciesInShift"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "PharmacyFilters"
        in: "body"
        schema:
         $ref: "#/definitions/PharmacyFilters"
      - name: "Content-type"
        in: "header"
        type: "string"
        required: true
      responses:
        200:
          description: "successful operation"
          schema:  
            $ref: "#/definitions/Pharmacy"
        204:
          description: "No Content"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      security:
        - google_jwt_client: []  
        
  "/commune":
     post:
      tags:
        - "commune"
      summary: "commune"
      description: ""
      operationId: "/commune"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Content-type"
        in: "header"
        type: "string"
        required: true
      responses:
        200:
          description: "successful operation"
          schema:  
            $ref: "#/definitions/Commune"
        204:
          description: "No Content"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      security:
        - google_jwt_client: []      
        
definitions:

  PharmacyFilters:
    type: "object"
    description: "Filter Pharmacy"
    properties:
     commune:
      type: "string"
     pharmacyName:
      type: "string"
      
  Pharmacy:
    type: "object"
    description: "contains the pharmacy information"
    properties:
     fecha:
      type: "string"
     localId:
      type: "string"
     localNombre:
      type: "string"
     comunaNombre:
      type: "string"
     localidadNombre:
      type: "string"
     localDireccion:
      type: "string"
     funcionamientoHoraApertura:
      type: "string"
     funcionamientoHoraCierre:
      type: "string"
     localTelefono:
      type: "string"
     localLat:
      type: "string"
     localLng:
      type: "string"
     funcionamientoDia:
      type: "string"
     fkRegion:
      type: "string"
     fkComuna:
      type: "string"
  
  Commune:
    type: "object"
    description: "contains the commune information"
    properties:
     name:
      type: "string"

  
securityDefinitions:
  # This section configures authentication using Google API Service Accounts
  # to sign a json web token. This is mostly used for server-to-server
  # communication.
  # configuracion del jwt
  google_jwt_client:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"